/**
 * Pure config-heal script builder (Phase 2 of "never silently lose an update").
 *
 * `buildConfigHealScript` turns an {@link AppRecord} into a single bash script
 * string that regenerates ONLY Caddy-layer artifacts (main vhost + active-route
 * for static apps) from the CURRENT generator templates, WITHOUT any content
 * redeploy (no git fetch/checkout/install/build/migrate/restart).
 *
 * The script is designed to run over ONE pinned SSH connection via `bash -s`
 * (stdin), identical to buildDeployScript's transport model.
 *
 * ---------------------------------------------------------------------------
 * v1 SCOPE — Caddy-layer artifacts only:
 *   (a) /etc/caddy/sites.d/00-main-<app>.caddy  (all apps with mainHost)
 *   (b) <appBase>/releases/.samohost-active-static.caddy  (static apps only)
 *
 * Out of scope in v1 (never touched):
 *   - env files (staging.env, .env, secrets)
 *   - systemd unit files and drop-ins
 *   - config.js or any app config file
 *   - .samohost-active-static.json (read-only; heal never writes it)
 *   - /etc/caddy/Caddyfile (the base import file)
 *   - preview env vhost files
 * ---------------------------------------------------------------------------
 *
 * SAFETY MODEL:
 *   1. Provenance gate: only overwrite files whose FIRST LINE is the exact
 *      samohost provenance header emitted by renderVhost. A hand-edited or
 *      unheadered file produces a 'drift-foreign' finding and is NEVER
 *      overwritten.
 *   2. Backup: `cp <live> <mktemp>` before any write.
 *   3. Staging: write regenerated content to `sudo /usr/bin/tee <staged>`,
 *      then `sudo /usr/bin/mv` staged → live (atomic).
 *   4. cmp: if ALL regenerated artifacts are identical to the live files
 *      → outcome 'no-drift', NO caddy reload, just stamp on the TypeScript side.
 *   5. caddy validate: validate the combined config before reload.
 *   6. Reload: `sudo /usr/bin/systemctl reload caddy` (full-path; exact
 *      NOPASSWD grant matches this path).
 *   7. Health probe: 10×3s curl loop (same as buildDeployScript).
 *   8. Rollback: on ANY failure, restore backups atomically, reload, re-probe.
 *
 * The builder is PURE: no I/O, fully deterministic, snapshot-stable.
 */

import type { AppRecord } from "../types.ts";
import { staticReleaseStatePaths } from "./static-root.ts";
import { renderVhost, planFromApp } from "../caddy/render.ts";
import { PHASE_PREFIX } from "./script.ts";

/** Phase names for the heal script. */
export type HealPhaseName =
  | "heal"
  | "caddy-reload"
  | "health"
  | "no-drift"
  | "rollback";

/** The exact provenance header that renderVhost emits as line 1. */
export const SAMOHOST_PROVENANCE_HEADER =
  "# generated by samohost/src/caddy/render.ts — do not edit by hand";

/** Health probe constants (mirrors buildDeployScript). */
const HEALTH_RETRIES = 10;
const HEALTH_SLEEP_SEC = 3;
const RESTART_SETTLE_SEC = 5;

/**
 * Single-quote a string for safe embedding in generated bash. Only
 * operator-controlled AppRecord values are interpolated — but quoting
 * guards against spaces and shell metacharacters in paths/domains.
 */
function sq(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

/** Emit a phase marker line. */
function marker(phase: HealPhaseName, status: "start" | "ok" | "fail"): string {
  return `echo "${PHASE_PREFIX}${phase}:${status}>>>"`;
}

/**
 * Build the remote config-heal script. The result is one self-contained bash
 * program intended for `bash -s` over a single SSH connection.
 *
 * Throws if:
 *   - app.mainHost is undefined (no main vhost to regenerate)
 */
export function buildConfigHealScript(app: AppRecord): string {
  if (app.mainHost === undefined) {
    throw new Error(
      `buildConfigHealScript: app "${app.name}" has no mainHost — ` +
        `cannot regenerate the main Caddy vhost without a mainHost`,
    );
  }

  const lines: string[] = [];
  const push = (...l: string[]): void => {
    for (const x of l) lines.push(x);
  };

  // ---- Artifact paths -------------------------------------------------------
  const mainVhostPath = `/etc/caddy/sites.d/00-main-${app.name}.caddy`;
  const stagedMainVhost = `/etc/caddy/sites.d/.samohost-heal-next-00-main-${app.name}.caddy`;
  const isStatic = app.kind === "static";
  const staticPaths = isStatic ? staticReleaseStatePaths(app.appDir) : undefined;

  // ---- Regenerated main vhost content (rendered at build time) --------------
  // planFromApp / renderVhost throws if mainHost is absent — already guarded above.
  const regeneratedMainVhost = renderVhost(planFromApp(app));

  // ---- Script header --------------------------------------------------------
  push(
    "#!/usr/bin/env bash",
    "# samohost config-heal script (generated; pushed over ssh stdin to `bash -s`).",
    "# Regenerates ONLY Caddy-layer artifacts from the current generator template.",
    "# NO content redeploy: no checkout, no install, no build, no migrate, no restart.",
    "set -euo pipefail",
    "",
    `SAMOHOST_MAIN_VHOST=${sq(mainVhostPath)}`,
    `SAMOHOST_STAGED_MAIN_VHOST=${sq(stagedMainVhost)}`,
    ...(isStatic && staticPaths !== undefined
      ? [
          `SAMOHOST_ACTIVE_STATE=${sq(staticPaths.activeState)}`,
          `SAMOHOST_ACTIVE_ROUTE=${sq(staticPaths.activeRoute)}`,
        ]
      : []),
    "",
  );

  // ---- Rollback function ----------------------------------------------------
  // Restores all backups atomically, re-validates, reloads, re-probes.
  push(
    "# rollback(): restore backed-up artifacts, re-validate, reload, re-probe.",
    "# Emits rollback:ok / rollback:fail and exits 1.",
    "rollback() {",
    "  local rb_ok=1",
    "  # Remove staged (uncommitted) artifact if present",
    `  sudo /usr/bin/rm -f ${sq(stagedMainVhost)} || true`,
    ...(isStatic && staticPaths !== undefined
      ? [
          '  sudo /usr/bin/rm -f "${SAMOHOST_ACTIVE_ROUTE_STAGED:-}" || true',
        ]
      : []),
    "  # Restore main vhost backup",
    '  if [[ "${SAMOHOST_MAIN_VHOST_HAD_BACKUP:-0}" == "1" && -f "${SAMOHOST_MAIN_VHOST_BACKUP:-}" ]]; then',
    `    if sudo /usr/bin/tee ${sq(stagedMainVhost)} >/dev/null < "$SAMOHOST_MAIN_VHOST_BACKUP"; then`,
    `      sudo /usr/bin/mv -- ${sq(stagedMainVhost)} ${sq(mainVhostPath)} || rb_ok=0`,
    "    else rb_ok=0; fi",
    "  fi",
    ...(isStatic && staticPaths !== undefined
      ? [
          "  # Restore active-route backup",
          '  if [[ "${SAMOHOST_ACTIVE_ROUTE_HAD_BACKUP:-0}" == "1" && -f "${SAMOHOST_ACTIVE_ROUTE_BACKUP:-}" ]]; then',
          '    local rb_tmp=""',
          '    rb_tmp=$(mktemp "${SAMOHOST_RELEASES_DIR}/.active-route.restore.XXXXXX") || rb_ok=0',
          '    if [[ -n "$rb_tmp" ]] && cp "$SAMOHOST_ACTIVE_ROUTE_BACKUP" "$rb_tmp" && chmod 0644 "$rb_tmp"; then',
          `      /usr/bin/mv -f "$rb_tmp" ${sq(staticPaths.activeRoute)} || rb_ok=0`,
          "    else rb_ok=0; fi",
          "  fi",
        ]
      : []),
    "  caddy validate --config /etc/caddy/Caddyfile >/dev/null || rb_ok=0",
    '  if [[ "$rb_ok" == "1" ]]; then sudo /usr/bin/systemctl reload caddy || rb_ok=0; fi',
    `  sleep ${RESTART_SETTLE_SEC}`,
    "  local rb_code",
    ...(app.mainListen === "cp-http80"
      ? [`  rb_code=$(curl -s -k -H ${sq(`Host: ${app.mainHost}`)} -o /dev/null -w "%{http_code}" --max-time 10 http://127.0.0.1/ || echo 000)`]
      : [`  rb_code=$(curl -s -k -H ${sq(`Host: ${app.mainHost}`)} -o /dev/null -w "%{http_code}" --max-time 10 https://127.0.0.1/ || echo 000)`]),
    '  if [[ "$rb_ok" == "1" && "$rb_code" == "200" ]]; then',
    `    ${marker("rollback", "ok")}`,
    "  else",
    `    ${marker("rollback", "fail")}`,
    '    echo "heal rollback health re-check failed (HTTP $rb_code) — manual intervention required" >&2',
    "  fi",
    "  # Cleanup backup temps",
    '  rm -f "${SAMOHOST_MAIN_VHOST_BACKUP:-}" || true',
    ...(isStatic && staticPaths !== undefined
      ? [
          '  rm -f "${SAMOHOST_ACTIVE_ROUTE_BACKUP:-}" || true',
          '  sudo /usr/bin/rm -f "${SAMOHOST_ACTIVE_ROUTE_STAGED:-}" || true',
        ]
      : []),
    "  exit 1",
    "}",
    "",
  );

  // ---- Heal start -----------------------------------------------------------
  push(
    marker("heal", "start"),
    "",
  );

  // ---- Track whether any artifact was actually changed ----------------------
  push(
    "SAMOHOST_HEAL_ANY_CHANGED=0",
    "SAMOHOST_HEAL_DRIFT_FOREIGN=0",
    "",
  );

  // ---- Main vhost artifact --------------------------------------------------
  push(
    "# --- main vhost: check provenance, backup, compare, stage ---",
    "SAMOHOST_MAIN_VHOST_BACKUP=\"$(mktemp)\"",
    "SAMOHOST_MAIN_VHOST_HAD_BACKUP=0",
    `if [[ -f ${sq(mainVhostPath)} ]]; then`,
    `  cp ${sq(mainVhostPath)} "$SAMOHOST_MAIN_VHOST_BACKUP"`,
    "  SAMOHOST_MAIN_VHOST_HAD_BACKUP=1",
    "  # Provenance gate: only overwrite files with the samohost header on line 1.",
    "  # A hand-edited file → drift-foreign finding; NEVER overwritten.",
    `  _provenance=$(head -1 ${sq(mainVhostPath)} 2>/dev/null || true)`,
    `  if [[ "$_provenance" != ${sq(SAMOHOST_PROVENANCE_HEADER)} ]]; then`,
    `    echo "drift-foreign: ${mainVhostPath} lacks samohost provenance header"`,
    "    SAMOHOST_HEAL_DRIFT_FOREIGN=1",
    "  else",
    "    # Write regenerated content to temp, compare with live",
    `    _new_main_vhost=$(mktemp)`,
    // Write the regenerated vhost (rendered at build time in TypeScript) to the temp file.
    // We use a heredoc to avoid shell-interpreting the vhost content.
    `    sudo /usr/bin/tee "$_new_main_vhost" >/dev/null <<'SAMOHOST_MAIN_VHOST_CONTENT'`,
    ...regeneratedMainVhost.split("\n"),
    "SAMOHOST_MAIN_VHOST_CONTENT",
    `    if cmp -s ${sq(mainVhostPath)} "$_new_main_vhost"; then`,
    `      rm -f "$_new_main_vhost"`,
    "      echo \"main vhost: no drift\"",
    "    else",
    "      # Stage: tee to staged path, then atomic mv",
    `      if sudo /usr/bin/tee ${sq(stagedMainVhost)} >/dev/null < "$_new_main_vhost"; then`,
    `        sudo /usr/bin/mv -- ${sq(stagedMainVhost)} ${sq(mainVhostPath)} || rollback`,
    "        echo \"main vhost: regenerated\"",
    "        SAMOHOST_HEAL_ANY_CHANGED=1",
    "      else",
    "        rollback",
    "      fi",
    `      rm -f "$_new_main_vhost"`,
    "    fi",
    "  fi",
    'elif [[ "${SAMOHOST_MAIN_VHOST_BACKUP:-}" != "" ]]; then',
    "  # File did not exist — no provenance check needed, write fresh",
    `  if sudo /usr/bin/tee ${sq(mainVhostPath)} >/dev/null <<'SAMOHOST_MAIN_VHOST_CONTENT'`,
    ...regeneratedMainVhost.split("\n"),
    "SAMOHOST_MAIN_VHOST_CONTENT",
    "  then",
    "    echo \"main vhost: created\"",
    "    SAMOHOST_HEAL_ANY_CHANGED=1",
    "  else rollback; fi",
    "fi",
    "",
  );

  // ---- Static app: active-route artifact ------------------------------------
  if (isStatic && staticPaths !== undefined) {
    push(
      "# --- static active-route: read releaseDir from active-state JSON, regenerate snippet ---",
      "# The active-route file is a raw Caddy snippet (NOT a site block / NOT renderVhost output).",
      "# Format: root * \"<releaseDir>\"\\ntry_files {path} {path}/ =404\\nfile_server\\nencode gzip\\n",
      `SAMOHOST_RELEASES_DIR=${sq(staticPaths.releasesDir)}`,
      `if [[ ! -f ${sq(staticPaths.activeState)} ]]; then`,
      `  echo "heal: active-state JSON not found at ${sq(staticPaths.activeState)} — skipping active-route regeneration"`,
      "else",
      "  # Parse releaseDir from the active-state JSON using python3.",
      "  # The active-state JSON schema: { schema:1, releaseDir: \"...\", staticRoot: \"...\", ... }",
      `  SAMOHOST_RELEASE_DIR=$(python3 -c "import json,sys; d=json.load(open(sys.argv[1])); print(d['releaseDir'])" ${sq(staticPaths.activeState)} 2>/dev/null || true)`,
      `  SAMOHOST_STATIC_ROOT=$(python3 -c "import json,sys; d=json.load(open(sys.argv[1])); print(d.get('staticRoot',''))" ${sq(staticPaths.activeState)} 2>/dev/null || true)`,
      '  if [[ -z "$SAMOHOST_RELEASE_DIR" ]]; then',
      `    echo "heal: could not read releaseDir from ${sq(staticPaths.activeState)} — skipping active-route regeneration"`,
      "  else",
      '    if [[ -n "$SAMOHOST_STATIC_ROOT" ]]; then',
      '      SAMOHOST_STATIC_DIR="$SAMOHOST_RELEASE_DIR/$SAMOHOST_STATIC_ROOT"',
      "    else",
      '      SAMOHOST_STATIC_DIR="$SAMOHOST_RELEASE_DIR"',
      "    fi",
      "    # Backup the live active-route snippet",
      '    SAMOHOST_ACTIVE_ROUTE_BACKUP="$(mktemp)"',
      "    SAMOHOST_ACTIVE_ROUTE_HAD_BACKUP=0",
      `    if [[ -f ${sq(staticPaths.activeRoute)} ]]; then`,
      `      cp ${sq(staticPaths.activeRoute)} "$SAMOHOST_ACTIVE_ROUTE_BACKUP"`,
      "      SAMOHOST_ACTIVE_ROUTE_HAD_BACKUP=1",
      "    fi",
      "    # Generate the regenerated active-route snippet to a temp file",
      '    SAMOHOST_ACTIVE_ROUTE_STAGED="$(mktemp "${SAMOHOST_RELEASES_DIR}/.active-route.heal.XXXXXX")"',
      '    if printf \'root * "%s"\\ntry_files {path} {path}/ =404\\nfile_server\\nencode gzip\\n\' "$SAMOHOST_STATIC_DIR" > "$SAMOHOST_ACTIVE_ROUTE_STAGED" && chmod 0644 "$SAMOHOST_ACTIVE_ROUTE_STAGED"; then',
      "      # cmp: if identical → no drift",
      `      if [[ -f ${sq(staticPaths.activeRoute)} ]] && cmp -s ${sq(staticPaths.activeRoute)} "$SAMOHOST_ACTIVE_ROUTE_STAGED"; then`,
      '        rm -f "$SAMOHOST_ACTIVE_ROUTE_STAGED"',
      '        echo "active-route: no drift"',
      "      else",
      "        # Atomic mv into place",
      `        if /usr/bin/mv -f "$SAMOHOST_ACTIVE_ROUTE_STAGED" ${sq(staticPaths.activeRoute)}; then`,
      '          echo "active-route: regenerated"',
      "          SAMOHOST_HEAL_ANY_CHANGED=1",
      "        else rollback; fi",
      "      fi",
      "    else",
      '      rm -f "$SAMOHOST_ACTIVE_ROUTE_STAGED" || true',
      "      rollback",
      "    fi",
      "  fi",
      "fi",
      "",
    );
  }

  // ---- If drift-foreign was detected, skip reload/health -------------------
  push(
    '# If any file had a foreign provenance (hand-edited), skip reload and report.',
    '# The app is still serving; we refuse to overwrite hand-edited config.',
    'if [[ "$SAMOHOST_HEAL_DRIFT_FOREIGN" == "1" ]]; then',
    '  echo "heal: drift-foreign finding present — skipping caddy reload (hand-edited files preserved)"',
    `  ${marker("heal", "ok")}`,
    "  exit 0",
    "fi",
    "",
  );

  // ---- If nothing changed, emit no-drift and exit --------------------------
  push(
    '# If no artifact was changed, emit no-drift and exit successfully.',
    '# generatorSha + lastHealAt are stamped on the TypeScript side regardless.',
    'if [[ "$SAMOHOST_HEAL_ANY_CHANGED" == "0" ]]; then',
    `  ${marker("no-drift", "ok")}`,
    "  exit 0",
    "fi",
    "",
  );

  // ---- Validate the combined Caddy config ----------------------------------
  push(
    "# --- validate: check the combined Caddy config before reload ---",
    "caddy validate --config /etc/caddy/Caddyfile >/dev/null || rollback",
    "",
  );

  // ---- caddy-reload --------------------------------------------------------
  push(
    "# --- caddy-reload: reload Caddy to serve the updated artifacts ---",
    "# Full-path systemctl: hardened host requires exact-path NOPASSWD grant.",
    marker("caddy-reload", "start"),
    "if sudo /usr/bin/systemctl reload caddy; then",
    `  sleep ${RESTART_SETTLE_SEC}`,
    `  ${marker("caddy-reload", "ok")}`,
    "else",
    `  ${marker("caddy-reload", "fail")}`,
    "  rollback",
    "fi",
    "",
  );

  // ---- Health probe --------------------------------------------------------
  push(
    "# --- health: poll the health URL, retrying; rollback on failure ---",
    marker("health", "start"),
    "health_ok=0",
    `for attempt in $(seq 1 ${HEALTH_RETRIES}); do`,
    ...(app.mainListen === "cp-http80"
      ? [`  code=$(curl -s -k -H ${sq(`Host: ${app.mainHost}`)} -o /dev/null -w "%{http_code}" --max-time 10 http://127.0.0.1/ || echo 000)`]
      : [`  code=$(curl -s -k -H ${sq(`Host: ${app.mainHost}`)} -o /dev/null -w "%{http_code}" --max-time 10 https://127.0.0.1/ || echo 000)`]),
    '  if [[ "$code" == "200" ]]; then health_ok=1; break; fi',
    `  sleep ${HEALTH_SLEEP_SEC}`,
    "done",
    'if [[ "$health_ok" == "1" ]]; then',
    `  ${marker("health", "ok")}`,
    "else",
    `  ${marker("health", "fail")}`,
    '  echo "heal health check failed after retries — rolling back" >&2',
    "  rollback",
    "fi",
    "",
  );

  // ---- Cleanup backups and emit heal:ok ------------------------------------
  push(
    "# Cleanup backup temps",
    'rm -f "${SAMOHOST_MAIN_VHOST_BACKUP:-}" || true',
    ...(isStatic && staticPaths !== undefined
      ? ['rm -f "${SAMOHOST_ACTIVE_ROUTE_BACKUP:-}" || true']
      : []),
    `${marker("heal", "ok")}`,
    'echo "heal complete: artifacts reconciled"',
    "",
  );

  return lines.join("\n");
}
