/**
 * Shared Caddy vhost renderer — prod + preview.
 *
 * Produces a Caddyfile site block from a {@link VhostPlan}. The plan is a
 * pure data structure so the renderer has zero I/O and is independently
 * testable. Two factory functions bridge the plan to samohost's domain model:
 *   - {@link planFromApp}  → production main-host vhost
 *   - {@link planFromEnv}  → per-branch preview vhost
 *
 * Security: EVERY embedded value (matcher path, regexp, respond body) is
 * double-quoted in the output. The spec validator bans `"` and `\` in user
 * values, so quoting is always safe and prevents whitespace/token injection.
 *
 * Order contract: Caddy `handle` is first-match. The renderer NEVER reorders
 * routes. The default `reverse_proxy` handle is always last.
 *
 * Back-compat: zero routes → BARE `reverse_proxy localhost:<defaultPort>` with
 * NO `handle {}` wrapper — Caddy-semantically identical to the single-service
 * preview form emitted by buildEnvCreateScript (src/env/script.ts vhost phase).
 * Wrapping in `handle {}` would add an extra subroute layer in adapted JSON,
 * silently changing the shape of every legacy env's vhost on next render.
 *
 * Idle-GC contract: every vhost emits a JSON access log to `plan.logFile`
 * (/var/log/caddy/<name>.log). The idle-GC pass reads that file for
 * `lastAccess` timestamps; never omit the log block.
 */

import type { AppSpec, EnvRecord, RouteSpec } from "../types.ts";
import { servicesOf } from "../app/services.ts";

// ---------------------------------------------------------------------------
// VhostPlan — the pure-data input to renderVhost
// ---------------------------------------------------------------------------

/**
 * A single routing rule within a {@link VhostPlan}.
 *
 * Exactly one of `matcher.path` | `matcher.regexp` is set.
 * Exactly one of `target.port` | `target.respond` is set.
 * `name` is required when `matcher.regexp` is set (Caddy named-matcher id).
 */
export interface VhostRoute {
  /** Caddy named-matcher id (e.g. "stream"). Required for regexp matchers. */
  name?: string;
  /**
   * Matcher: exactly one field present.
   *  - `{ path: "/webhook*" }` → inline Caddy path matcher in the handle line.
   *  - `{ regexp: "^/..." }` → Caddy `path_regexp` named matcher (needs `name`).
   */
  matcher: { path?: string } | { regexp?: string };
  /**
   * Target: exactly one field present.
   *  - `{ port: 8888 }` → `reverse_proxy localhost:<port>`.
   *  - `{ respond: { status, body } }` → Caddy `respond "<body>" <status>`.
   */
  target: { port: number } | { respond: { status: number; body: string } };
}

/**
 * A fully-resolved description of one Caddy vhost site block.
 *
 *  - `listen: "cp-http80"` → `http://<host>:80 { ... }` (control-plane HTTP;
 *    TLS terminated upstream by CF tunnel or a parent proxy).
 *  - `listen: "tls-internal"` → `<host> { tls internal ... }` (preview form;
 *    Caddy's own internal CA issues certs for *.samo.cat).
 */
export interface VhostPlan {
  /** FQDN served by this vhost (e.g. "samograph.samo.team"). */
  host: string;
  /** Caddy listen + TLS mode. */
  listen: "cp-http80" | "tls-internal";
  /**
   * Routing rules in EXACT spec order. NEVER sorted — Caddy `handle` is
   * first-match-wins. The default `reverse_proxy` handle is appended LAST
   * by the renderer; do not include it here.
   */
  routes: VhostRoute[];
  /** Port for the catch-all default `reverse_proxy` handle. */
  defaultPort: number;
  /** Absolute path for the JSON access log (idle-GC contract). */
  logFile: string;
}

// ---------------------------------------------------------------------------
// renderVhost
// ---------------------------------------------------------------------------

/**
 * Emit a Caddyfile site block from `plan`.
 *
 * Output conventions:
 *   - Tab-indented (matches fleet hand-authored files).
 *   - All embedded values double-quoted.
 *   - Named matchers (regexp) declared at the TOP of the block, in route order.
 *   - Handle blocks follow in EXACT spec order, default handle LAST.
 *   - JSON access log block always present.
 *   - Provenance comment at top (ignored by caddy adapt).
 */
export function renderVhost(plan: VhostPlan): string {
  const lines: string[] = [];

  // Provenance header (stripped by caddy adapt; harmless to hand-read files)
  lines.push(
    "# generated by samohost/src/caddy/render.ts — do not edit by hand",
  );

  // Site address + opening brace
  if (plan.listen === "cp-http80") {
    lines.push(`http://${plan.host}:80 {`);
  } else {
    // tls-internal: bare hostname, Caddy defaults to :443
    lines.push(`${plan.host} {`);
    lines.push(`\ttls internal`);
  }

  // Pass 1: declare all named matchers (regexp) at block scope, in route order.
  // Named matchers must be declared before (or alongside) their first reference
  // in a handle block. Declaring all upfront matches the fleet convention.
  for (const route of plan.routes) {
    if (route.name !== undefined) {
      const m = route.matcher;
      if ("regexp" in m && m.regexp !== undefined) {
        lines.push(`\t@${route.name} path_regexp "${m.regexp}"`);
      }
    }
  }

  // Pass 2: handle blocks in EXACT spec order (NEVER sort).
  for (const route of plan.routes) {
    const m = route.matcher;

    // Derive the matcher token used in the handle line.
    let matcherToken: string;
    if (route.name !== undefined && "regexp" in m) {
      // Named matcher reference: `handle @stream { ... }`
      matcherToken = `@${route.name}`;
    } else if ("path" in m && m.path !== undefined) {
      // Inline path matcher — double-quoted to prevent token splitting on spaces.
      matcherToken = `"${m.path}"`;
    } else {
      // A route with no name, no path, and no regexp is a programming error —
      // the manifest validator must never produce such a plan. Throw instead of
      // emitting an empty matcher token (which would produce a catch-all route
      // that shadows every subsequent handle, silently breaking routing).
      // Defense-in-depth: this path is unreachable via validated manifests today
      // but safer than silently emitting a shadowing catch-all.
      throw new Error(
        `renderVhost: route has no valid matcher (no name/path/regexp) — ` +
          `this indicates a malformed VhostPlan that bypassed manifest validation; ` +
          `check the route spec at plan.host="${plan.host}"`,
      );
    }

    const target = route.target;

    if ("respond" in target) {
      // Static response: `respond "<body>" <status>`
      const { status, body } = target.respond;
      lines.push(`\thandle ${matcherToken} {`);
      lines.push(`\t\trespond "${body}" ${status}`);
      lines.push(`\t}`);
    } else {
      // Reverse proxy
      const port = target.port;
      if (matcherToken !== "") {
        lines.push(`\thandle ${matcherToken} {`);
      } else {
        lines.push(`\thandle {`);
      }
      lines.push(`\t\treverse_proxy localhost:${port}`);
      lines.push(`\t}`);
    }
  }

  // Default reverse_proxy.
  // Zero routes (legacy single-service): emit the BARE directive with no
  // `handle {}` wrapper — matches buildEnvCreateScript's printf template
  // (src/env/script.ts vhost phase) exactly. The `handle {}` wrapper creates
  // an extra subroute layer in adapted JSON that diverges from today's live
  // single-service preview form and would silently change every legacy env's
  // vhost on next render.
  //
  // Routes present (multi-service): wrap in a catch-all `handle {}` so it
  // acts as Caddy's last-resort fallback after all matcher-specific handles.
  if (plan.routes.length === 0) {
    lines.push(`\treverse_proxy localhost:${plan.defaultPort}`);
  } else {
    lines.push(`\thandle {`);
    lines.push(`\t\treverse_proxy localhost:${plan.defaultPort}`);
    lines.push(`\t}`);
  }

  // JSON access log (idle-GC contract: must be present on every vhost).
  lines.push(`\tlog {`);
  lines.push(`\t\toutput file ${plan.logFile}`);
  lines.push(`\t\tformat json`);
  lines.push(`\t}`);

  lines.push(`}`);

  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// planFromApp — production main-host vhost
// ---------------------------------------------------------------------------

/**
 * Build a {@link VhostPlan} for an app's production main-host vhost.
 *
 *  - host = app.mainHost (required; callers must ensure it is set)
 *  - listen from app.mainListen (default "cp-http80")
 *  - routes + ports resolved via {@link servicesOf}
 *  - defaultPort = port of app.defaultListener
 *  - logFile = `/var/log/caddy/<app.name>-prod.log`
 *
 * Throws if:
 *   - app.mainHost is absent
 *   - servicesOf() throws (missing defaultListener, dangling listener name)
 *   - a route references a listener that doesn't exist in the service topology
 */
export function planFromApp(app: AppSpec): VhostPlan {
  if (app.mainHost === undefined) {
    throw new Error(
      `planFromApp: app "${app.name}" has no mainHost — ` +
        `set mainHost before calling planFromApp`,
    );
  }

  const { services, routes, defaultListener } = servicesOf(app);

  // Build listener-name → port map
  const portMap = new Map<string, number>();
  for (const svc of services) {
    for (const listener of svc.listeners) {
      portMap.set(listener.name, listener.port);
    }
  }

  const defaultPort = portMap.get(defaultListener);
  if (defaultPort === undefined) {
    throw new Error(
      `planFromApp: defaultListener "${defaultListener}" not found in ` +
        `services of app "${app.name}"`,
    );
  }

  const planRoutes = routeSpecsToVhostRoutes(routes, portMap, app.name);

  // Map AppSpec.mainListen ("cp-http80" | "tls") to VhostPlan.listen.
  // "tls" → "tls-internal" is the closest current VhostPlan equivalent.
  const listen: "cp-http80" | "tls-internal" =
    app.mainListen === "tls" ? "tls-internal" : "cp-http80";

  return {
    host: app.mainHost,
    listen,
    routes: planRoutes,
    defaultPort,
    logFile: `/var/log/caddy/${app.name}-prod.log`,
  };
}

// ---------------------------------------------------------------------------
// planFromEnv — per-branch preview vhost
// ---------------------------------------------------------------------------

/**
 * Build a {@link VhostPlan} for a preview env vhost.
 *
 *  - host = target.vhost (e.g. "samograph-main.samo.cat")
 *  - listen = "tls-internal" (always; previews use Caddy's internal CA)
 *  - ports from target.ports (multi-service) or target.port (legacy)
 *  - defaultPort = target.ports[defaultListener] or target.port (legacy)
 *  - logFile = `/var/log/caddy/<target.name>.log`
 *
 * Throws if:
 *   - defaultListener is not resolvable to an allocated port
 *   - a route "to" references a listener with no allocated port
 */
export function planFromEnv(app: AppSpec, target: EnvRecord): VhostPlan {
  const { services, routes, defaultListener } = servicesOf(app);

  // Build listener-name → allocated port map from target.ports (multi-service)
  // or fall back to target.port for legacy single-service envs.
  const portMap = new Map<string, number>();

  if (target.ports !== undefined) {
    for (const [name, port] of Object.entries(target.ports)) {
      portMap.set(name, port);
    }
  } else {
    // Legacy single-service: all listeners map to the one allocated port.
    portMap.set(defaultListener, target.port);
    for (const svc of services) {
      for (const listener of svc.listeners) {
        if (!portMap.has(listener.name)) {
          portMap.set(listener.name, target.port);
        }
      }
    }
  }

  const defaultPort = portMap.get(defaultListener);
  if (defaultPort === undefined) {
    throw new Error(
      `planFromEnv: defaultListener "${defaultListener}" not found in ` +
        `target.ports for env "${target.name}"`,
    );
  }

  const planRoutes = routeSpecsToVhostRoutes(routes, portMap, target.name);

  return {
    host: target.vhost,
    listen: "tls-internal",
    routes: planRoutes,
    defaultPort,
    logFile: `/var/log/caddy/${target.name}.log`,
  };
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Convert an array of {@link RouteSpec} (from servicesOf) to {@link VhostRoute}
 * objects, resolving listener names to port numbers via `portMap`.
 */
function routeSpecsToVhostRoutes(
  routes: RouteSpec[],
  portMap: Map<string, number>,
  context: string,
): VhostRoute[] {
  return routes.map((r: RouteSpec): VhostRoute => {
    // Matcher
    const matcher: { path?: string } | { regexp?: string } =
      r.matchRegexp !== undefined
        ? { regexp: r.matchRegexp }
        : { path: r.matchPath };

    // Target
    let target: { port: number } | { respond: { status: number; body: string } };

    if (r.respond !== undefined) {
      target = { respond: r.respond };
    } else if (r.to !== undefined) {
      const port = portMap.get(r.to);
      if (port === undefined) {
        throw new Error(
          `routeSpecsToVhostRoutes [${context}]: route "to" references ` +
            `listener "${r.to}" which has no allocated port ` +
            `(known: ${[...portMap.keys()].join(", ") || "(none)"})`,
        );
      }
      target = { port };
    } else {
      throw new Error(
        `routeSpecsToVhostRoutes [${context}]: route has neither "to" nor "respond"`,
      );
    }

    return { name: r.name, matcher, target };
  });
}
